language: erlang 

notifications:
    email: skattelmann@gmail.com

otp_release: 
    - R14B04

before_install:

#    setup for tetrapak 

    - cd ..

    - export ERL_LIBS=$ERL_LIBS:`pwd`/

    - git clone https://github.com/travelping/tetrapak.git
    - cd tetrapak;make;sudo make install
    - export PATH=$PATH:`pwd`/bin/
    - sudo ln /usr/lib/erlang/lib/tetrapak-0.4.24.1~3c49c86/bin/tetrapak /usr/bin/ -sf
    - cd ..

    - git clone https://github.com/skattelmann/tetrapak_deps.git
    - cd tetrapak_deps;
    # -git checkout tp-integration;
    - chmod +x installer.sh

    #./installer.sh

    - mkdir -p temp
    - cd temp
    - export ERL_LIBS=$ERL_LIBS:`pwd`/
        
    - git clone https://github.com/travelping/sh.git
    - cd sh
    - tetrapak install -local
    - cd ..

    - git clone https://github.com/travelping/erlsemver.git
    - cd erlsemver
    - tetrapak install -local
    - cd ..

    - git clone https://github.com/liveforeverx/redbug.git
    - cd redbug
    - tetrapak install -local
    - cd ..

    - git clone https://github.com/travelping/erlgit.git
    - cd erlgit
    - tetrapak install -local
    - cd ..

    - git clone https://github.com/skattelmann/tetrapak_deps.git
    - cd tetrapak_deps
    #- git checkout tp-integration
    - tetrapak install -local
    - cd ../..
    #- sudo rm -rf temp

    - cd ..
    - ls -a
    - cd hello/


install:
    - tetrapak build

script:
    - tetrapak test -smp enable

