language: erlang 

notifications:
    email: skattelmann@gmail.com

otp_release: 
    - R14B04

before_install:

#    setup for tetrapak 
    
    - cd ..
    - git clone https://github.com/travelping/tetrapak.git
    - cd tetrapak;make;sudo make install
    - ls bin/
    - sudo ln /usr/lib/erlang/lib/tetrapak-0.4.24.1~3c49c86/bin/tetrapak /usr/bin/ -sf
    - cd ..

    - git clone https://github.com/travelping/tetrapak_deps.git
    - cd tetrapak_deps;git checkout tp-integration;chmod +x installer.sh

    - mkdir -p temp
    - cd temp
        
    - git clone https://github.com/travelping/sh.git
    - cd sh
    - sudo ../../../tetrapak/bin/tetrapak install -local
    - cd ..

    - git clone https://github.com/travelping/erlsemver.git
    - cd erlsemver
    - sudo ../../../tetrapak/bin/tetrapak install -local
    - cd ..

    - git clone https://github.com/liveforeverx/redbug.git
    - cd redbug
    - sudo ../../../tetrapak/bin/tetrapak install -local
    - cd ..

    - git clone https://github.com/travelping/erlgit.git
    - cd erlgit
    - sudo ../../../tetrapak/bin/tetrapak install -local
    - cd ..

    - git clone git@git.tpip.net:tetrapak_deps.git
    - cd tetrapak_deps
    - git checkout tp-integration
    - sudo ../../../tetrapak/bin/tetrapak install -local
    - cd ../..
    - sudo rm -rf temp

    - cd ../hello/


install:
    - ../tetrapak/bin/tetrapak build

script:
    - tetrapak test -smp enable

